const items = [
  {
      id: '001',
      image: 'images/1.jpg',
      company: 'Dell',
      item_name: 'Dell Laptop',
      original_price: 50000,
      current_price: 40000,
      discount_percentage:20,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 4.5,
          count: 1400,
      },
  },
  {
      id: '002',
      image: 'images/2.jpg',
      company: 'Microsoft',
      item_name: 'Microsoft Laptop ',
      original_price: 60000,
      current_price: 48000,
      discount_percentage:20,
      return_period: 14,
      delivery_date: '15 Oct 2024',
      rating: {
          stars: 4.3,
          count: 24,
      },
  },
  {
      id: '003',
      image: 'images/3.jpg',
      company: 'Acer',
      item_name: 'Acer Laptop',
      original_price: 30000,
      current_price: 24000,
      discount_percentage: 20,
      return_period: 14,
      delivery_date: '22 Oct 2024',
      rating: {
          stars: 4.1,
          count: 249,
      },
  },
  {
      id: '004',
      image: 'images/4.jpg',
      company: 'Hp',
      item_name: 'Hp Laptop',
      original_price: 36000,
      current_price: 36000,
      discount_percentage: 0,
      return_period: 14,
      delivery_date: '10 sep 2024',
      rating: {
          stars: 5.0,
          count: 10,
      },
  },
  {
      id: '005',
      image: 'images/5.jpg',
      company: 'Lenovo',
      item_name: 'Lenovo Laptop',
      original_price: 25000,
      current_price: 20000,
      discount_percentage: 20,
      return_period: 14,
      delivery_date: '10 Oct 2023',
      rating: {
          stars: 4.2,
          count: 3500,
      },
  },
  {
      id: '006',
      image: 'images/6.jpg',
      company: 'MSI',
      item_name: 'MSI Laptop',
      original_price: 14995,
      current_price: 14995,
      discount_percentage: 0,
      return_period: 14,
      delivery_date: '1 Oct 2024',
      rating: {
          stars: 0.0,
          count: 0,
      },
  },
  {
      id: '007',
      image: 'images/7.jpg',
      company: 'Asus',
      item_name: 'Asus Laptop',
      original_price: 15999,
      current_price: 15999,
      discount_percentage: 0,
      rating: {
          stars: 4.2,
          count: 388,
      },
  },
  {
      id: '008',
      image: 'images/8.jpg',
      company: 'HCL',
      item_name: 'HCL Laptop',
      original_price: 28555,
      current_price: 28555,
      discount_percentage: 0,
      return_period: 14,
      delivery_date: '10 Oct 2024',
      rating: {
          stars: 4.2,
          count: 5200,
      },
  }
];